services:
  - type: web
    name: portfolio-backend
    env: docker
    dockerContext: ./server
    dockerCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Ajoutez ici vos autres variables d'environnement nécessaires
    # - key: MONGODB_URI
    #   value: your-mongodb-uri
    # - key: JWT_SECRET
    #   value: your-jwt-secret
    plan: free
