# render.yaml
services:
  - type: web
    name: portfolio-singor-backend
    env: node
    buildCommand: |
      echo "Installation des dépendances..."
      npm install --production=false --no-package-lock --no-audit --progress=false
      echo "Installation des types Node.js..."
      npm install --save-dev @types/node@20.11.19
      echo "Construction de l'application..."
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: false
    buildCache:
      clearOnSuccess: false
    plan: free
    autoDeploy: true
