# render.yaml
services:
  - type: web
    name: portfolio-singor-backend
    env: node
    buildCommand: |
      echo "Installation des dépendances..."
      npm ci --prefer-offline --no-audit --progress=false
      echo "Construction de l'application..."
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    buildCache:
      clearOnSuccess: true
    plan: free
    autoDeploy: true
