# render.yaml
services:
  - type: web
    name: portfolio-singor-backend
    env: node
    buildCommand: |
      echo "Installation des dépendances..."
      npm install
      echo "Construction de l'application..."
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
